#!/usr/bin/env bash

case $BLOCK_BUTTON in
  1) light -S 10;;
  2) light -S 40;;
  3) light -S 80;;
  4) light -A 10;;
  5) light -U 10;;
esac

light=$(light -G)

printf %.0f $light && echo ""
printf %.0f $light && echo ""
