#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "<span color='red'><span font='Font Awesome 5 Pro'>\uf00d \uf240</span></span>"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is
    # available for each battery separately, although state and remaining
    # time for overall block is shown in the status of the first battery
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            percentleft_batteries.append(int(commasplitstatus[1].rstrip("%\n")))
            commasplitstatus_batteries.append(commasplitstatus)

    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))


    # stands for charging
    FA_LIGHTNING = "<span color='#E6DB74'><span font='Font Awesome 5 Pro'>\uf376</span></span>"

    # stands for plugged in
    FA_PLUG = "<span font='Font Awesome 5 Pro'>\uf240</span>"

    if state == "Discharging":
        if percentleft < 10:
            fulltext = "<span font='Font Awesome 5 Pro'>\uf244</span> "
        elif percentleft < 20:
            fulltext = "<span font='Font Awesome 5 Pro'>\uf243</span> "
        elif percentleft < 40:
            fulltext = "<span font='Font Awesome 5 Pro'>\uf242</span> "
        elif percentleft < 80:
            fulltext = "<span font='Font Awesome 5 Pro'>\uf241</span> "
        else:
            fulltext = "<span font='Font Awesome 5 Pro'>\uf240</span> "
    elif state == "Full":
        fulltext = FA_PLUG + " "
    elif state == "Unknown":
        fulltext =  "<span font='Font Awesome 5 Pro'>\uf377</span> "
    else:
        fulltext = FA_LIGHTNING + " " + FA_PLUG + " "

    def color(percent):
        if percent < 10:
            return "#FF5555"
        if percent < 20:
            return "#E6DB74"
        if percent < 80:
            return "#999999"
        return "#8BE9FD"

    form =  '<span color="{}">{}%</span>'
    fulltext += form.format(color(percentleft), percentleft)

print(fulltext)
print(fulltext)
