#!/usr/bin/env bash

temperature="$(redshift -p | grep -P -o '[0-9]+K')"
color="#FF5555"

if [[ $(pidof redshift | wc -w) = 0 ]]; then
  temperature="optimal"
  color="#8BE9FD"
fi

if [[ ${temperature::-1} -gt "4999" ]]; then
  color="#E6DB74"
fi

echo "$temperature"
echo "$temperature"
echo "$color"
