#!/usr/bin/env bash

instance="$(fd enp /sys/class/net/ | head -n 1)"
label=""
state="down"

if [[ -f "$instance/operstate" ]]; then
  state=$(cat "$instance/operstate")
fi

if [[ "$state" == "down" ]]; then
  echo "$label"
  echo "$label"
  echo "#FF5555"
  exit 0
fi

speed="$(cat "$instance/speed" 2> /dev/null)"

echo "$label $speed"
echo "$label $speed"
echo "#8BE9FD"
