#!/usr/bin/env bash

notifications=$(hub api notifications | jq '. | length')

if [[ -z "$notifications" ]]; then
  exit 0
fi

echo "$notifications"
echo "$notifications"

if [[ $notifications -gt 0 ]]; then
  echo "#E6DB74"
fi

