#!/usr/bin/env bash

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

echo "$load"
echo "$load"

awk -v cpus="$cpus" -v cpuload="$load" '
  BEGIN {
    if (cpus <= cpuload) {
        print "#FF5555";
        exit 33;
    }
  }
'
