#!/usr/bin/env bash

label=""
state="$(cat /sys/class/net/$BLOCK_INSTANCE/operstate)"

if [ "$state" != "up" ]; then
	echo "$label"
	echo "$label"
	echo "#FF5555"
	exit 0
fi

quality="$(grep $BLOCK_INSTANCE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')"
ssid="$(iwgetid -r)"

echo "$label $ssid @ $quality%"
echo "$label $ssid @ $quality%"

if [[ $quality -gt 50 ]]; then
    echo "#8BE9FD"
elif [[ $quality -gt 24 ]] && [[ $quality -lt 51 ]]; then
    echo "#EDC33D"
elif [[ $quality -lt 25 ]]; then
    echo "#FF5555"
fi
