# Catppuccin Latte (Muted) for zsh-syntax-highlighting.
# https://github.com/catppuccin/zsh-syntax-highlighting

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[comment]='fg=#92949f'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#207068'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#207068'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#207068'
ZSH_HIGHLIGHT_STYLES[function]='fg=#2850a8'
ZSH_HIGHLIGHT_STYLES[command]='fg=#2850a8'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#2850a8,italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#a85820,italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#a85820'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#a85820'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#7c32a8'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#7c32a8'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#2850a8'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#984080'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#984080'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#287028'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#287028'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#287028'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#b82530'
ZSH_HIGHLIGHT_STYLES[path]='fg=#806010,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#984080,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#806010,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#984080,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#7c32a8'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#4c4e5e'
ZSH_HIGHLIGHT_STYLES[default]='fg=#4c4e5e'
