#  ╺━┓┏━┓╻ ╻┏━╸┏┓╻╻ ╻
#  ┏━┛┗━┓┣━┫┣╸ ┃┗┫┃┏┛
#  ┗━╸┗━┛╹ ╹┗━╸╹ ╹┗┛

if [[ -f $ZDOTDIR/secretenv ]]; then
  source $ZDOTDIR/secretenv
fi

# Docker.
export DOCKER_HOST="unix://${XDG_RUNTIME_DIR}/docker.sock"

# GPG.
export GPG_TTY="$(tty)"
export SSH_AGENT_PID=""
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"

# Dynamically add all dev binary directories.
dev_bins=("$HOME/dev"/*/bin(N/))
(( $#dev_bins )) && DEV_BINS=${(j.:.)dev_bins}

if [[ -z "$DEFAULT_NODE_VERSION" ]]; then
  DEFAULT_NODE_VERSION=$($SCRIPTS/default-node-version.sh)
fi

[[ -n "$DEFAULT_NODE_VERSION" ]] && export PATH="$DEFAULT_NODE_VERSION:$PATH"
[[ -n "$DEV_BINS" ]] && export PATH="$DEV_BINS:$PATH"
[[ -d "$HOME/.local/bin" ]] && export PATH="$HOME/.local/bin:$PATH"

# Terminal options.
export AUTOPAIR_INHIBIT_INIT=1
export KEYTIMEOUT=0
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'
export ZSH_AUTOSUGGEST_USE_ASYNC=1
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZVM_KEYTIMEOUT=0.125
export ZVM_READKEY_ENGINE=$ZVM_READKEY_ENGINE_NEX
export ZVM_SYSTEM_CLIPBOARD_ENABLED=true
export ZVM_VI_HIGHLIGHT_BACKGROUND=#b6bdd0 # bg_visual
export ZVM_VI_HIGHLIGHT_FOREGROUND=#383e45 # fg

# Pass options.
export PASSWORD_STORE_GENERATED_LENGTH=24
export PASSWORD_STORE_GPG_OPTS=--no-throw-keyids

# Color options.
export GREP_COLORS='mt=30;44'
export LESS='-R'
export LESSHISTFILE=-
export LESSOPEN='| bat --color=always %s'
export LS_COLORS="$(vivid generate catppuccin-latte-muted)"

# Font rendering.
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"

# Misc options.
export GTK_THEME=Orchis-Light
