[theme]
theme = "gruvbox-dark"
[theme.overrides]
idle_bg = ""
idle_fg = "#bdae93"
info_bg = ""
info_fg = "#ebdbb2"
good_bg = ""
good_fg = "#83a598"
warning_bg = ""
warning_fg = "#fabd2f"
critical_bg = ""
critical_fg = "#fb4934"
separator = " "
separator_bg = ""
separator_fg = ""

[icons]
icons = "material-nf"

[[block]]
block = "temperature"
format = " $icon $average"
format_alt = " $icon $min min, $max max, $average avg"
interval = 5
info = 70
chip = "*-isa-*"
[block.theme_overrides]
idle_bg = ""
idle_fg = "#8ec07c"

[[block]]
block = "memory"
interval = 5
format = "$mem_used"
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = "$max_frequency $utilization $barchart "

[[block]]
block = "backlight"
cycle = [30, 70]

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/screensaver"
json = true
signal = 6
[[block.click]]
button = "left"
cmd = "$SCRIPTS/toggles/screensaver.sh"

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/hue-shift"
interval = 5
json = true
signal = 8
[[block.click]]
button = "left"
cmd = "$SCRIPTS/toggles/redshift.sh"
[block.theme_overrides]
idle_fg = "#8ec07c"
good_fg = "#fabd2f"
warning_fg = "#d3869b"

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/gpu-mode"
signal = 10
[block.theme_overrides]
idle_bg = "#3c3836"
idle_fg = "#ebdbb2"

[[block]]
block = "net"
format = " $icon{ $ssid|}"
[block.theme_overrides]
idle_fg = "#8ec07c"

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/vpn"
interval = 10
json = true
[[block.click]]
button = "left"
cmd = "mullvad-vpn"

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/github"
interval = 60
json = true
[[block.click]]
button = "left"
cmd = "$BROWSER 'https://github.com/notifications'"

[[block]]
block = "custom"
command = "$SCRIPTS/blocks/arch"
interval = 300
json = true
signal = 4
[[block.click]]
button = "left"
cmd = "term paru"

[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
step_width = 5
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
step_width = 5
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
[block.format]
full = "$timestamp.datetime(f:'%Y-%m-%d %H:%M') "

[[block]]
block = "battery"
format = " $icon $percentage "
good = 80
info = 60
warning = 30
critical = 15
full_format = " $icon "
[block.theme_overrides]
idle_bg = "#83a598"
idle_fg = "#222222"
info_bg = "#d3869b"
info_fg = "#222222"
good_bg = "#8ec07c"
good_fg = "#222222"
warning_bg = "#fabd2f"
warning_fg = "#222222"
critical_bg = "#fb4934"
critical_fg = "#222222"
