#!/usr/bin/env bash

while read -r file
do
  fullpath="$(pwd)/$file"

  case "$1" in
    "g")    gimp "$file" & ;;
    "d")    trash "$file" ;;
    "f")    convert -flop "$file" "$file" ;;
    "r")    convert -rotate 90 "$file" "$file" ;;
    "R")    convert -rotate -90 "$file" "$file" ;;
    "y")    echo -n "$file" | xsel -ib ;;
    "Y")    echo -n "$fullpath" | xsel -ib ;;
  esac
done
