# vim:fileencoding=utf-8

[app]
overall = { bg = "#d4d6de" }

[mgr]
cwd = { fg = "#207068" }

find_keyword = { fg = "#806010", italic = true }
find_position = { fg = "#984080", bg = "reset", italic = true }

marker_copied = { fg = "#287028", bg = "#287028" }
marker_cut = { fg = "#b82530", bg = "#b82530" }
marker_marked = { fg = "#207068", bg = "#207068" }
marker_selected = { fg = "#2850a8", bg = "#2850a8" }

count_copied = { fg = "#d4d6de", bg = "#287028" }
count_cut = { fg = "#d4d6de", bg = "#b82530" }
count_selected = { fg = "#d4d6de", bg = "#2850a8" }

border_symbol = "│"
border_style = { fg = "#616475" }

syntect_theme = "~/.config/bat/themes/catppuccin-latte.tmTheme"

[tabs]
active = { fg = "#d4d6de", bg = "#1e2028", bold = true }
inactive = { fg = "#1e2028", bg = "#999ca7" }

[mode]
normal_main = { fg = "#d4d6de", bg = "#2850a8", bold = true }
normal_alt = { fg = "#2850a8", bg = "#adb0ba" }

select_main = { fg = "#d4d6de", bg = "#287028", bold = true }
select_alt = { fg = "#287028", bg = "#adb0ba" }

unset_main = { fg = "#d4d6de", bg = "#a05858", bold = true }
unset_alt = { fg = "#a05858", bg = "#adb0ba" }

[indicator]
parent = { fg = "#d4d6de", bg = "#1e2028" }
current = { fg = "#d4d6de", bg = "#2850a8" }
preview = { fg = "#d4d6de", bg = "#1e2028" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#287028", bg = "#999ca7" }
progress_error = { fg = "#806010", bg = "#b82530" }

perm_type = { fg = "#2850a8" }
perm_read = { fg = "#806010" }
perm_write = { fg = "#b82530" }
perm_exec = { fg = "#287028" }
perm_sep = { fg = "#616475" }

[input]
border = { fg = "#2850a8" }
title = {}
value = {}
selected = { reversed = true }

[pick]
border = { fg = "#5858a0" }
active = { fg = "#984080" }
inactive = {}

[confirm]
border = { fg = "#2850a8" }
title = { fg = "#2850a8" }
body = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}

[cmp]
border = { fg = "#5858a0" }

[tasks]
border = { fg = "#5858a0" }
title = {}
hovered = { fg = "#984080", bold = true }

[which]
mask = { bg = "#adb0ba" }
cand = { fg = "#207068" }
rest = { fg = "#3e4152" }
desc = { fg = "#984080" }
separator = "  "
separator_style = { fg = "#868998" }

[help]
on = { fg = "#207068" }
run = { fg = "#984080" }
desc = { fg = "#3e4152" }
hovered = { bg = "#868998", bold = true }
footer = { fg = "#1e2028", bg = "#999ca7" }

[notify]
title_info = { fg = "#207068" }
title_warn = { fg = "#806010" }
title_error = { fg = "#b82530" }

[spot]
border = { fg = "#2850a8" }
title = { fg = "#2850a8" }
tbl_cell = { fg = "#2850a8", reversed = true }
tbl_col = { bold = true }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "#207068" },
  { mime = "{audio,video}/*", fg = "#806010" },

  # Archives
  { mime = "application/*zip", fg = "#984080" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#984080" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#287028" },

  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#999ca7" },

  # Special file
  { url = "*", is = "orphan", bg = "#b82530" },
  { url = "*", is = "exec", fg = "#287028" },

  # Dummy file
  { url = "*", is = "dummy", bg = "#b82530" },
  { url = "*/", is = "dummy", bg = "#b82530" },

  # Fallback
  { url = "*/", fg = "#2850a8" },
]
